export default function PrivacyPolicy() {
  return (
    <div className="w-full bg-brand-bg relative overflow-hidden">
      
      {/* Aurora Radial Glows */}
      <div className="aurora-glow" />
      <div className="aurora-glow-cyan" />

      {/* 🍵 Section 1: Hero Block */}
      <section className="relative border-b border-brand-neon/20 py-20 md:py-24 grid-bg-glow">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="max-w-3xl">
            <span className="inline-block border border-brand-neon bg-brand-neon/15 px-3 py-1 text-xs uppercase font-bold tracking-widest text-brand-neon shadow-[0_0_10px_rgba(0,255,136,0.15)] mb-6">
              Security Protocol Manifesto
            </span>
            <h1 className="font-serif text-5xl md:text-6xl font-bold tracking-tight text-brand-white leading-[1.05] mb-8">
              Privacy & Data <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-neon via-brand-cyan to-brand-gold">
                Security Policy
              </span>
            </h1>
            <p className="text-xs font-mono text-brand-cyan tracking-wider uppercase">
              Last Updated Protocol Revision: May 18, 2026
            </p>
          </div>
        </div>
      </section>

      {/* 📜 Section 2: Policy Details - Raised descriptions from text-xs to text-sm */}
      <section className="py-20 bg-brand-panel">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 space-y-12 text-brand-white/80">
          
          <div className="space-y-4">
            <h2 className="font-serif text-3xl font-bold text-brand-white">1. Agronomic Image Data Security</h2>
            <p className="text-sm font-light leading-relaxed">
              When using the Tea Leaf Disease Analyzer, you upload visual RGB leaf images. These images are transmitted securely to our local model servers and sandboxed under randomized UUID hashes. Your crops' intellectual property is fully respected: we never sell, share, or license uploaded leaf images to third-party chemical vendors or agrochemical companies.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="font-serif text-3xl font-bold text-brand-white">2. Automatic Telemetry Deletion Log</h2>
            <p className="text-sm font-light leading-relaxed">
              We operate under a strict "Zero Storage Bloat" mandate. All crop visuals uploaded to the temporary inference queue are automatically and permanently purged from our storage nodes every 7 days. If you require long-term diagnostic history logging, you must opt-in to our premium Estate Pro plan where images are held in localized secure database clusters.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="font-serif text-3xl font-bold text-brand-white">3. Local Cookie Consent & Telemetry</h2>
            <p className="text-sm font-light leading-relaxed">
              We employ lightweight analytical cookies and standard local storage values strictly to retain visual session history, block spam submissions, and cache the model's neural layers in order to speed up diagnostic latency for estate fields with slow cellular network connections.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="font-serif text-3xl font-bold text-brand-white">4. Agronomist Disclaimers</h2>
            <p className="text-sm font-light leading-relaxed">
              Diagnostic outputs generated by our ensembled neural models represent statistical predictions. The platform does not guarantee biological absolute truths. Estate owners should consult local certified agronomists or plant pathologists prior to initiating massive agrochemical or chemical spray programs based on AI prediction scores.
            </p>
          </div>

        </div>
      </section>

    </div>
  );
}
