import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_contact_email(name, sender_email, estate, message):
    smtp_email = os.environ.get("SMTP_EMAIL", "your_email@gmail.com")
    smtp_password = os.environ.get("SMTP_PASSWORD", "your_app_password")
    smtp_server = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = os.environ.get("SMTP_PORT", "587")
    
    # Check if the values are placeholders or empty
    is_placeholder = (
        not smtp_email or 
        smtp_email == "your_email@gmail.com" or 
        not smtp_password or 
        smtp_password == "your_app_password"
    )
    
    if is_placeholder:
        print("[MOCK EMAIL] SMTP credentials are not configured or using placeholders. Logging email message.")
        # Ensure uploads folder exists
        uploads_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "uploads")
        os.makedirs(uploads_dir, exist_ok=True)
        
        log_path = os.path.join(uploads_dir, "contact_emails.log")
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(f"--- EMAIL TRANSMITTED (MOCK MODE) ---\n")
                f.write(f"From Name: {name}\n")
                f.write(f"From Email: {sender_email}\n")
                f.write(f"Estate: {estate}\n")
                f.write(f"Message:\n{message}\n")
                f.write(f"------------------------------------\n\n")
            return True, "Mock sent: logged to uploads/contact_emails.log"
        except Exception as file_err:
            print(f"Failed to log email mock to file: {file_err}")
            return False, f"Failed to log email: {file_err}"
            
    try:
        # Create message container
        msg = MIMEMultipart()
        msg['From'] = smtp_email
        msg['To'] = smtp_email  # Sends the ticket copy to yourself (the admin)
        msg['Reply-To'] = sender_email
        msg['Subject'] = f"🍵 Tea Diagnostics Telemetry: {name} ({estate or 'No Estate'})"
        
        body = f"""
        Tea Diagnostics Research Desk - Telemetry Ticket Recieved
        
        Sender Information:
        - Name: {name}
        - Email: {sender_email}
        - Estate / Cooperative: {estate or 'Not Specified'}
        
        Message Content:
        ---------------------------------------------------------
        {message}
        ---------------------------------------------------------
        
        This notification was auto-generated by the Tea Diagnostics AI Server.
        """
        msg.attach(MIMEText(body, 'plain'))
        
        # Connect and Send
        server = smtplib.SMTP(smtp_server, int(smtp_port))
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.sendmail(smtp_email, smtp_email, msg.as_string())
        server.quit()
        
        print("[SMTP EMAIL] Successfully transmitted contact ticket via SMTP.")
        return True, "Email sent successfully"
    except Exception as e:
        print(f"[SMTP EMAIL] Failed to send email: {e}")
        # Log failed email so message is not lost
        uploads_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "uploads")
        os.makedirs(uploads_dir, exist_ok=True)
        log_path = os.path.join(uploads_dir, "contact_emails_failed.log")
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(f"--- FAILED EMAIL (Error: {e}) ---\n")
                f.write(f"From Name: {name}\n")
                f.write(f"From Email: {sender_email}\n")
                f.write(f"Estate: {estate}\n")
                f.write(f"Message:\n{message}\n")
                f.write(f"---------------------------------\n\n")
        except Exception:
            pass
        return False, str(e)
